version: '3'
services:
  db:
    image: mysql:8.0
    container_name: company_hiring_mysql
    restart: always
    ports:
      - 33306:3306
    environment:
      MYSQL_DATABASE: company_hiring
      MYSQL_ROOT_PASSWORD: root123!@#
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64